// <auto-generated />
using System;
using GoodHabits.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoodHabits.Database.Migrations
{
    [DbContext(typeof(GoodHabitsDbContext))]
    [Migration("20240711003724_Todos")]
    partial class Todos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoodHabits.Database.Entities.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Habits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d94df76f-a3cd-4501-919c-b09cc3420f37"),
                            Description = "Bluewave - Become a francophone",
                            Name = "Bluewave - Learn French",
                            TenantName = "Bluewave"
                        },
                        new
                        {
                            Id = new Guid("2b4a30af-cd49-4359-9738-7b552609e6d1"),
                            Description = "Become a francophone",
                            Name = "Learn French",
                            TenantName = "CloudSphere"
                        },
                        new
                        {
                            Id = new Guid("4a4399ab-729d-4b08-ba87-7a4e9b179376"),
                            Description = "Become a SaaSer",
                            Name = "Learn Saad",
                            TenantName = "CloudSphere"
                        },
                        new
                        {
                            Id = new Guid("e2aa93c9-b426-4db9-888f-ced925803e1a"),
                            Description = "Become a master",
                            Name = "Learn Multi Tenancy",
                            TenantName = "CloudSphere"
                        });
                });

            modelBuilder.Entity("GoodHabits.Database.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TodoItem")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
